### PR TITLE
Modify quickstart.md

### PR DESCRIPTION
**Pull request by lowtower**
Add factories to configuration for single and multiple container usage

### CODE REVIEW

**Comment by lowtower** [comment]
Hello @froschdesign ,

this PR adds only documentation following the discussions in [issue 56](https://github.com/zendframework/zend-navigation/issues/56) and [PR 61](https://github.com/zendframework/zend-navigation/pull/61#issuecomment-285740599).

Cheers ,
LT.

**Comment by froschdesign** [comment]
@lowtower 
Thanks for contribution, but there is no need for manual adding. I will extend the `ConfigProvider`class. The goal: keep it simple!

Again, thanks!

**Comment by lowtower** [comment]
Yes, that's better.
Was already wondering, why manual adding was necessary at all.
Any news, why it is not merged to master?
Cheers,
LT.

**Comment by froschdesign** [comment]
> Was already wondering, why manual adding was necessary at all.

To test the first draft.

> Any news, why it is not merged to master?

The zend-expressive feature is still work in progress and we will change the structure of components. I will work on this in the next days.

---
Btw. Are you already using this feature / branch? If so, can you give some feedback? For example:

* Is something missing?
* Is something to complicated?
* Do you see problems?
* Do you see space for improvements?
* Do we need more documentation?

Thank you in advance!

**Comment by lowtower** [comment]
Hello Frank,

at the moment, I am just playing around and trying to (re-)write the expressive tutorial from Ralf Eggert with `zend-expressive` v2.0, adding some extra parts, e.g. the tutorials for `zend-mvc`, just like `zend-navigation` and `zend-pagination`.

At the moment, I am struggling with using partials for menu and breadcrumbs (for bootstrap style).
I don't know where to put the partials (I have a `src/App/view/partial` path for generic code) and tell `zend-navigation` to use it properly (with `->setPartial()` of course, but which path?).

In the next steps, I will implement `rbac` or `acl` and will then come back with questions, I suppose ;-)

Thanks in advance,
LT.

**Comment by lowtower** [comment]
Hello Frank,

just some short questions:

- is it possible to define partials for the link `<li>`-tag only and not for the whole menu `<ul>`-tag?
- or is there a way of wrapping tags around the `<li>`, or pre-/append something to the link `<li>`-tag?
- `zend-expressive` uses the notation `namespace::partialName` instead of the full path to the partial such es `zend-mvc`, am I right? Could be added to the documentation.
- what is the recommendation for the place to store `generic`/`app-wide` partials? I put them into `/templates/partials`.

Thanks in advance,
LT.

**Pull request closed without merging**
